name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  tntreport:
    description: Show the TNT report!
    permission: ServerOperator
  tntreload:
    description: Reload plugin!
    permission: ServerOperator