name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  example:
    aliases: ["none"]
    description: "This command does nothing."