# Config file for plugin TNTReporter.
detectBroken: False
detectPlaced: False
detectActivated: True
# interruptExplosion: False
# allowedWorlds:
#   - world
# allowedDimensions:
#   - overworld
#   - nether
#   - end
