# Config file for plugin TNTReporter.

# Activate or deactivate console log for broken blocks of TNT.
# DEFAULT: True
detectBroken: False

# Activate or deactivate console log for placed blocks of TNT.
# DEFAULT: True
detectPlaced: False

# Activate or deactivate console log for activated blocks of TNT.
# DEFAULT: True
detectActivated: True

# interruptExplosion: False