name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  tntreporter:
    description: Main command for TNTReporter plugin
    usage: /tntreporter <help|report|reload>
    permission: tntreporter.use
  tntreporterReport:
    description: Show the TNT report!
    usage: /tntreporter report
    permission: tntreporter.report
  tntreporterReload:
    description: Reload plugin!
    usage: /tntreporter reload
    permission: tntreporter.reload